# Generated by Django 5.1.3 on 2024-11-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobxcrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.company'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.company'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.company'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.menubutton'),
        ),
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.branch'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.company'),
        ),
        migrations.AddField(
            model_name='question',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobxcrm.vacancy'),
        ),
    ]
